# Generated by Django 5.0.9 on 2026-09-12 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('url', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('body_type', models.CharField(choices=[('none', 'none'), ('raw', 'raw'), ('json', 'json'), ('form-urlencoded', 'form-urlencoded'), ('multipart', 'multipart')], default='none', max_length=20)),
                ('body', models.JSONField(blank=True, default=None, null=True)),
                ('auth_type', models.CharField(choices=[('none', 'none'), ('bearer', 'bearer'), ('basic', 'basic'), ('api_key', 'api_key')], default='none', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=None, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('extract_rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='collections.collection')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['collection', 'order'], name='saved_reque_collect_fe2529_idx')],
            },
        ),
    ]
