# Generated by Django 5.0.9 on 2026-09-13 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('saved_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAssertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('status_code', 'Status code equals'), ('response_time_lt', 'Response time less than'), ('header_exists', 'Header exists'), ('header_equals', 'Header equals'), ('json_field_exists', 'JSON field exists'), ('json_field_equals', 'JSON field equals'), ('body_contains', 'Body contains')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='saved_requests.savedrequest')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assertion_name', models.CharField(max_length=255)),
                ('passed', models.BooleanField()),
                ('actual_value', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='testing.testassertion')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='history.requesthistory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testassertion',
            index=models.Index(fields=['saved_request', 'order'], name='testing_tes_saved_r_2fe2fc_idx'),
        ),
    ]
