# Generated by Django 5.0.9 on 2026-09-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collections.collection'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['parent'], name='collections_parent__7b255f_idx'),
        ),
    ]
