# Generated by Django 5.0.9 on 2026-09-12 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saved_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('request_snapshot', models.JSONField(default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=None, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL)),
                ('saved_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='saved_requests.savedrequest')),
            ],
            options={
                'verbose_name_plural': 'request history',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['owner', '-executed_at'], name='history_req_owner_i_fc29a9_idx')],
            },
        ),
    ]
